-- Source mapping tables + PFM raw source/medium traffic for Product Views

CREATE TABLE IF NOT EXISTS public.smart_source_mapping_channels (
  id text PRIMARY KEY,
  name text NOT NULL,
  color text NOT NULL DEFAULT '#94a3b8',
  sort_order integer NOT NULL DEFAULT 100,
  is_unmapped boolean NOT NULL DEFAULT false,
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.smart_source_mapping_rules (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  raw_source text NOT NULL,
  raw_medium text NOT NULL,
  channel_id text NOT NULL REFERENCES public.smart_source_mapping_channels (id) ON DELETE CASCADE,
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (raw_source, raw_medium)
);

CREATE INDEX IF NOT EXISTS idx_smart_source_mapping_rules_channel
  ON public.smart_source_mapping_rules (channel_id);

ALTER TABLE public.smart_source_mapping_channels ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.smart_source_mapping_rules ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS smart_source_mapping_channels_read ON public.smart_source_mapping_channels;
CREATE POLICY smart_source_mapping_channels_read
  ON public.smart_source_mapping_channels FOR SELECT TO anon, authenticated
  USING (true);

DROP POLICY IF EXISTS smart_source_mapping_channels_write ON public.smart_source_mapping_channels;
CREATE POLICY smart_source_mapping_channels_write
  ON public.smart_source_mapping_channels FOR ALL TO anon, authenticated, service_role
  USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS smart_source_mapping_rules_read ON public.smart_source_mapping_rules;
CREATE POLICY smart_source_mapping_rules_read
  ON public.smart_source_mapping_rules FOR SELECT TO anon, authenticated
  USING (true);

DROP POLICY IF EXISTS smart_source_mapping_rules_write ON public.smart_source_mapping_rules;
CREATE POLICY smart_source_mapping_rules_write
  ON public.smart_source_mapping_rules FOR ALL TO anon, authenticated, service_role
  USING (true) WITH CHECK (true);

GRANT SELECT, INSERT, UPDATE, DELETE ON public.smart_source_mapping_channels TO anon, authenticated, service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.smart_source_mapping_rules TO anon, authenticated, service_role;
GRANT USAGE, SELECT ON SEQUENCE public.smart_source_mapping_rules_id_seq TO anon, authenticated, service_role;

-- Seed defaults if empty
INSERT INTO public.smart_source_mapping_channels (id, name, color, sort_order, is_unmapped)
SELECT * FROM (VALUES
  ('organic-search', 'Organic Search', '#2563eb', 10, false),
  ('direct', 'Direct', '#16a34a', 20, false),
  ('paid-search', 'Paid Search', '#d97706', 30, false),
  ('paid-social', 'Paid Social', '#dc2626', 40, false),
  ('organic-social', 'Organic Social', '#7c3aed', 50, false),
  ('referral', 'Referral', '#0891b2', 60, false),
  ('email', 'Email', '#db2777', 70, false),
  ('unmapped', 'Unmapped', '#94a3b8', 999, true)
) AS v(id, name, color, sort_order, is_unmapped)
WHERE NOT EXISTS (SELECT 1 FROM public.smart_source_mapping_channels LIMIT 1);

INSERT INTO public.smart_source_mapping_rules (raw_source, raw_medium, channel_id)
SELECT * FROM (VALUES
  ('google', 'organic', 'organic-search'),
  ('bing', 'organic', 'organic-search'),
  ('yahoo', 'organic', 'organic-search'),
  ('(direct)', '(none)', 'direct'),
  ('google', 'cpc', 'paid-search'),
  ('bing', 'cpc', 'paid-search'),
  ('facebook', 'paid', 'paid-social'),
  ('instagram', 'paid', 'paid-social'),
  ('tiktok', 'paid', 'paid-social'),
  ('facebook', 'organic', 'organic-social'),
  ('instagram', 'organic', 'organic-social'),
  ('newsletter', 'email', 'email'),
  ('klaviyo', 'email', 'email')
) AS v(raw_source, raw_medium, channel_id)
WHERE NOT EXISTS (SELECT 1 FROM public.smart_source_mapping_rules LIMIT 1)
ON CONFLICT (raw_source, raw_medium) DO NOTHING;

-- Raw source/medium for Pure for Men (page views + product views)
CREATE OR REPLACE FUNCTION public.get_pfm_raw_source_medium_traffic(
  p_from date,
  p_to date,
  p_client_id text DEFAULT '001'
)
RETURNS TABLE (
  raw_source text,
  raw_medium text,
  raw_channel text,
  page_views bigint,
  vdp_views bigint
)
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT
    COALESCE(NULLIF(TRIM(d.source), ''), '(direct)') AS raw_source,
    COALESCE(NULLIF(TRIM(d.medium), ''), '(none)') AS raw_medium,
    COALESCE(NULLIF(TRIM(d.channel), ''), '(not set)') AS raw_channel,
    COALESCE(SUM(d.views), 0)::bigint AS page_views,
    COALESCE(
      SUM(d.views) FILTER (WHERE public.is_pfm_product_page_path(d.page_path)),
      0
    )::bigint AS vdp_views
  FROM public.chipper_pfm_ga4_data d
  WHERE d.client_id = p_client_id
    AND d.report_date >= p_from
    AND d.report_date <= p_to
    AND COALESCE(d.page_path, '') NOT ILIKE '%/web-pixels%'
  GROUP BY 1, 2, 3
  HAVING COALESCE(SUM(d.views), 0) > 0
  ORDER BY page_views DESC;
$$;

REVOKE ALL ON FUNCTION public.get_pfm_raw_source_medium_traffic(date, date, text) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.get_pfm_raw_source_medium_traffic(date, date, text) TO anon, authenticated, service_role;
