-- Document schema already applied remotely (Agency Dashboard).
-- PFM Google Ads entity tables + sync state + unified view.
-- Edge function: pfm-google-ads-sync

CREATE TABLE IF NOT EXISTS public.pfm_google_ads_accounts (
  customer_id bigint PRIMARY KEY,
  client_id text,
  descriptive_name text,
  is_active boolean NOT NULL DEFAULT true,
  last_synced timestamptz,
  sync_status text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.pfm_google_ads_campaign (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  client_id text,
  customer_id bigint NOT NULL,
  platform text NOT NULL DEFAULT 'google',
  campaign_id text NOT NULL,
  name text,
  status text,
  channel_type text,
  budget_amount numeric,
  budget_period text,
  bidding_strategy text,
  optimization_score numeric,
  geo_target_type_setting text,
  report_from date,
  report_to date,
  impressions bigint DEFAULT 0,
  clicks bigint DEFAULT 0,
  cost numeric DEFAULT 0,
  conversions numeric DEFAULT 0,
  ctr numeric,
  average_cpc numeric,
  last_synced_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (customer_id, platform, campaign_id)
);

CREATE INDEX IF NOT EXISTS idx_pfm_gads_campaign_client
  ON public.pfm_google_ads_campaign (client_id);

CREATE TABLE IF NOT EXISTS public.pfm_google_ads_ad_group (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  client_id text,
  customer_id bigint NOT NULL,
  platform text NOT NULL DEFAULT 'google',
  campaign_id text NOT NULL,
  ad_group_id text NOT NULL,
  name text,
  status text,
  report_from date,
  report_to date,
  impressions bigint DEFAULT 0,
  clicks bigint DEFAULT 0,
  cost numeric DEFAULT 0,
  conversions numeric DEFAULT 0,
  last_synced_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (customer_id, platform, ad_group_id)
);

CREATE INDEX IF NOT EXISTS idx_pfm_gads_ad_group_campaign
  ON public.pfm_google_ads_ad_group (customer_id, campaign_id);

CREATE TABLE IF NOT EXISTS public.pfm_google_ads_ad (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  client_id text,
  customer_id bigint NOT NULL,
  platform text NOT NULL DEFAULT 'google',
  campaign_id text NOT NULL,
  ad_group_id text NOT NULL,
  ad_id text NOT NULL,
  ad_type text,
  status text,
  approval_status text,
  ad_strength text,
  final_urls text[],
  headlines text[],
  descriptions text[],
  report_from date,
  report_to date,
  impressions bigint DEFAULT 0,
  clicks bigint DEFAULT 0,
  cost numeric DEFAULT 0,
  conversions numeric DEFAULT 0,
  last_synced_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (customer_id, platform, ad_id)
);

CREATE INDEX IF NOT EXISTS idx_pfm_gads_ad_group
  ON public.pfm_google_ads_ad (customer_id, ad_group_id);

CREATE TABLE IF NOT EXISTS public.pfm_google_ads_keyword (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  client_id text,
  customer_id bigint NOT NULL,
  platform text NOT NULL DEFAULT 'google',
  campaign_id text NOT NULL,
  ad_group_id text NOT NULL,
  criterion_id text NOT NULL,
  text text,
  match_type text,
  status text,
  quality_score integer,
  negative boolean DEFAULT false,
  report_from date,
  report_to date,
  impressions bigint DEFAULT 0,
  clicks bigint DEFAULT 0,
  cost numeric DEFAULT 0,
  conversions numeric DEFAULT 0,
  average_cpc numeric,
  last_synced_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (customer_id, platform, ad_group_id, criterion_id)
);

CREATE INDEX IF NOT EXISTS idx_pfm_gads_kw_group
  ON public.pfm_google_ads_keyword (customer_id, ad_group_id);

CREATE TABLE IF NOT EXISTS public.pfm_google_ads_search_term (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  client_id text,
  customer_id bigint NOT NULL,
  platform text NOT NULL DEFAULT 'google',
  report_from date,
  report_to date,
  report_date date NOT NULL,
  campaign_id text NOT NULL,
  ad_group_id text NOT NULL,
  term text NOT NULL,
  term_status text,
  matched_keyword text,
  match_type text,
  impressions bigint DEFAULT 0,
  clicks bigint DEFAULT 0,
  cost numeric DEFAULT 0,
  conversions numeric DEFAULT 0,
  last_synced_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (customer_id, platform, report_date, ad_group_id, term)
);

CREATE INDEX IF NOT EXISTS idx_pfm_gads_st_date
  ON public.pfm_google_ads_search_term (customer_id, report_date);

CREATE TABLE IF NOT EXISTS public.pfm_google_ads_sync_state (
  id text PRIMARY KEY DEFAULT 'default',
  customer_id bigint NOT NULL,
  report_from date NOT NULL,
  report_to date NOT NULL,
  phase text NOT NULL DEFAULT 'campaigns',
  chunk_from date,
  chunk_days integer NOT NULL DEFAULT 2,
  status text NOT NULL DEFAULT 'idle',
  last_error text,
  last_upserted integer,
  last_message text,
  last_run_at timestamptz,
  updated_at timestamptz NOT NULL DEFAULT now()
);

-- Unified read view (campaign + ad_group rows)
CREATE OR REPLACE VIEW public.pfm_google_ads_data AS
SELECT
  'campaign'::text AS entity_type,
  customer_id,
  client_id,
  campaign_id AS entity_id,
  name AS entity_name,
  status,
  report_from,
  report_to,
  impressions,
  clicks,
  cost,
  conversions,
  last_synced_at
FROM public.pfm_google_ads_campaign
UNION ALL
SELECT
  'ad_group'::text AS entity_type,
  customer_id,
  client_id,
  ad_group_id AS entity_id,
  name AS entity_name,
  status,
  report_from,
  report_to,
  impressions,
  clicks,
  cost,
  conversions,
  last_synced_at
FROM public.pfm_google_ads_ad_group;

ALTER TABLE public.pfm_google_ads_accounts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.pfm_google_ads_campaign ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.pfm_google_ads_ad_group ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.pfm_google_ads_ad ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.pfm_google_ads_keyword ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.pfm_google_ads_search_term ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.pfm_google_ads_sync_state ENABLE ROW LEVEL SECURITY;
